language: node_js
node_js: 
  - 12.11.0
addons:
  sonarcloud:
    organization: "kevinsuasnabar"
    token:
      secure: $SONAR_TOKEN
    projectKey: CalculatorNodeJS
    sources: './app'

script:
  - sonar-scanner